### default ressources used by snakemake (applied to all rules)
__default__:
  job-name: "{rule}"
  time: "96:00:00" # max run time "hours:minutes:seconds"
  ntasks: 1 # nb of processes
  cpus-per-task: 4 # nb of cores for each process(1 process)
  mem: "60G"
  nodes: 1 # Requirements nodes/servers (default: 1)
  ntasks-per-node: 1 # Requirements cpu/core/task (default: 1)
  output: "slurm_logs/{rule}.%N.%j.out"
  error: "slurm_logs/{rule}.%N.%j.err"
  mail-type: END,FAIL #email notification
  mail-user: your.email@here.fr

create_chr_config_file:
  output: "/dev/null"
  mail-type: NONE 
  mem: "5G"
  cpus-per-task: 1

generate_fai_index:
  output: "/dev/null"
  mem: "100G"
  cpus-per-task: 20

split_index:
  output: "/dev/null"
  mail-type: NONE 
  mem: "5G"
  cpus-per-task: 1

run_msprime:
  error: "/dev/null"
  output: "/dev/null"
  mail-type: NONE 
  cpus-per-task: 1
  mem: "50G"

compress_sim_vcf:
  error: "/dev/null"
  output: "/dev/null"
  mail-type: NONE 

index_sim_vcf:
    error: "/dev/null"
    output: "/dev/null"
    mail-type: NONE 

add_header:
  output: "/dev/null"
  mail-type: NONE 
  cpus-per-task: 1

sort_header:
  output: "/dev/null"
  mail-type: NONE 
  cpus-per-task: 1

remove_vcf_header:
  output: "/dev/null"
  mail-type: NONE 
  cpus-per-task: 1
  
extract_vcf_header:
  output: "/dev/null"
  mail-type: NONE 
  cpus-per-task: 1

unzip_simulated_vcf:
  output: "/dev/null"
  mail-type: NONE 

unzip_input_fasta:
  output: "/dev/null"
  mail-type: NONE 

compress_vcf_for_griaffe:
  mail-type: NONE 

generate_variants:
  mem: "200G"

index_giraffe:
  mail-type: NONE
  mem: "150G"

sort_vcf:
  mail-type: NONE
  mem: "150G"

construct_graph:
  mail-type: NONE
  mem: "150G"

vg_to_gfa:
  mem: "150G"

gbz_to_gfa:
  mail-type: NONE
  mem: "150G"
  
graph_to_fasta:
  mem: "150G"