restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

## added snakemake settings
keep-going: True # Go on with independent jobs if a job fails
rerun-incomplete: True # Re-run all jobs the output of which is recognized as incomplete.
# keep-incomplete: True # keep results even if failed
# unlock: True