samples:
  test_sample1:        
    fasta_gz: "test_genome.fa.gz"  # Fasta file
    population_size: 5              # Population size (Ne)
    mutation_rate: 1e-7             # Mutation rate (r)
    recombination_rate:
    sample_size: 2      
